version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b '0.0.0.0'"

    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
